# Generated by Django 5.2.8 on 2025-11-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_quiz_alter_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz_type',
            field=models.CharField(choices=[('MATH', 'Math'), ('SCI', 'Science'), ('HIST', 'History')], default='MATH', max_length=10),
        ),
    ]
